version: "3"
services:
  db:
    image: mariadb:10
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: axiangcoding
      MYSQL_PASSWORD: axiangcoding
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
#    volumes:
#      - ./volume/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    # restart: always
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis:6-alpine
    # restart: always
    ports:
      - "6379:6379"
  mq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"