// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gin-template/internal/app/biz"
	"gin-template/internal/app/conf"
	"gin-template/internal/app/data"
	"gin-template/internal/app/server"
	"gin-template/internal/app/server/http/controller"
)

// Injectors from wirt.go:

func initApp(confData *conf.Data, confServer *conf.Server) (*App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(db)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUseCase := biz.NewUserUseCase(userRepo)
	userController := controller.NewUserController(userUseCase)
	httpServer := server.NewHTTPServer(userController)
	app := newApp(httpServer)
	return app, func() {
		cleanup()
	}, nil
}
